name: 'Features / PRs'

on: [push, pull_request]
  branches:
    - *
    - !master # all branches except master

env:
  # Workaround for GitVersionTask bug in combination with .NET Core SDK 3.1.200
  # (see, e.g., https://github.com/dotnet/sdk/issues/10878 and https://github.com/GitTools/GitVersion/issues/2063)
  MSBUILDSINGLELOADCONTEXT: 1

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2
      with:
        persist-credentials: false

    - name: Fetch all branches (used by GitVersion)
      run: git fetch --prune --unshallow

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.200

    - name: Restore library
      run: dotnet restore src/BlazorLazyLoading.sln --disable-parallel -p:BLLUseLocalNugetPackages=true

    - name: Build library
      run: dotnet build src/BlazorLazyLoading.sln -c Release --disable-parallel -p:BLLUseLocalNugetPackages=true
  
    - name: Test library
      run: dotnet test src/BlazorLazyLoading.sln -c Release -p:BLLUseLocalNugetPackages=true

    - name: Pack library
      run: dotnet pack src/BlazorLazyLoading.sln -c Release --disable-parallel -p:BLLUseLocalNugetPackages=true

    - name: Restore demo
      run: dotnet restore demo/Demo.sln --disable-parallel -p:BLLUseLocalNugetPackages=true

    - name: Build demo
      run: dotnet build demo/Demo.sln -c Release --disable-parallel -p:BLLUseLocalNugetPackages=true

    - name: Publish demo
      run: dotnet publish demo/ServerHost/ServerHost.csproj -c Release --disable-parallel -p:BLLUseLocalNugetPackages=true -o output/demo

    - name: Test demo
      run: dotnet test demo/Demo.sln -c Release -p:BLLUseLocalNugetPackages=true

    - name: Upload artifacts
      uses: actions/upload-artifact@v1
      with:
        name: output
        path: output
